export default {
  id: "ethics",
  code: "BB362218523 · TB102-2026",
  bar: "var(--c-ethics)",
  tint: "var(--c-ethics-bg)",
  nameTR: "Bilimsel Araştırma Teknikleri İle Araştırma ve Yayın Etiği",
  nameEN: "Research Techniques & Publication Ethics",
  topics: [
    { id: "process", name: "Araştırma Süreci ve Tasarımı" },
    { id: "misconduct", name: "Araştırma Etiği İhlalleri" },
    { id: "authorship", name: "Yazarlık ve Yayın" },
    { id: "integrity", name: "Araştırma Bütünlüğü ve Yönetişimi" }
  ],
  cards: [
    // --- process ---
    { id:"lit-review", topic:"process", tr:"Literatür Taraması", en:"Literature review", def:"Bir konudaki mevcut araştırmaların sistematik biçimde incelenmesi; boşlukları belirlemek ve yeni bir çalışmayı konumlandırmak için kullanılır.", defEn:"A systematic examination of existing research on a topic, used to identify gaps and situate a new study." },
    { id:"research-hypothesis", topic:"process", tr:"Araştırma Hipotezi", en:"Research hypothesis", def:"Veri toplanmadan önce ortaya konan, bir olguya ilişkin test edilebilir önerilen açıklama.", defEn:"A proposed, testable explanation for a phenomenon, stated before data collection." },
    { id:"peer-review", topic:"process", tr:"Hakem Değerlendirmesi", en:"Peer review", def:"Bir makalenin yayımlanmadan önce alanındaki uzmanlarca bağımsız olarak değerlendirilmesi.", defEn:"Independent evaluation of a manuscript by experts in the field before publication." },
    { id:"research-design", topic:"process", tr:"Araştırma Deseni", en:"Research design", def:"Bir çalışmanın bileşenlerini tutarlı ve mantıklı biçimde bir araya getiren genel strateji.", defEn:"The overall strategy for integrating a study's components in a coherent, logical way." },
    { id:"research-question", topic:"process", tr:"Araştırma Sorusu", en:"Research question", def:"Bir çalışmanın tam olarak neyi araştırmayı amaçladığını tanımlayan, odaklanmış ve cevaplanabilir soru; hipotez ve yöntem bundan türetilir.", defEn:"The focused, answerable question that defines exactly what a study aims to investigate, from which the hypothesis and methodology follow." },
    { id:"independent-variable", topic:"process", tr:"Bağımsız Değişken", en:"Independent variable", def:"Araştırmacının bilinçli olarak değiştirdiği veya kategorilere ayırdığı, başka bir değişken üzerinde etkili olduğu varsayılan değişken.", defEn:"The variable a researcher deliberately manipulates or categorizes, assumed to cause an effect on another variable." },
    { id:"dependent-variable", topic:"process", tr:"Bağımlı Değişken", en:"Dependent variable", def:"Bağımsız değişkendeki değişikliklere tepki verip vermediğini görmek için ölçülen sonuç değişkeni.", defEn:"The outcome variable measured to see whether it responds to changes in the independent variable." },
    { id:"validity", topic:"process", tr:"Geçerlilik", en:"Validity", def:"Bir çalışmanın, ölçtüğünü iddia ettiği şeyi gerçekten ne ölçüde ölçtüğü ve sonuçlarının kanıtlarla ne kadar desteklendiği.", defEn:"The extent to which a study actually measures what it claims to measure, and its conclusions are justified by the evidence." },
    { id:"reliability", topic:"process", tr:"Güvenilirlik", en:"Reliability", def:"Bir ölçüm veya yöntemin tutarlılığı — aynı koşullarda tekrarlandığında aynı sonucu verip vermediği.", defEn:"The consistency of a measurement or method — whether repeating it under the same conditions produces the same result." },
    { id:"control-group", topic:"process", tr:"Kontrol Grubu", en:"Control group", def:"Test edilen uygulamayı almayan, uygulamanın gerçek etkisini ayırt etmek için kullanılan karşılaştırma grubu.", defEn:"A comparison group that does not receive the treatment being tested, used to isolate the treatment's actual effect." },
    { id:"replication", topic:"process", tr:"Tekrarlanabilirlik", en:"Replication", def:"Bağımsız bir araştırmacının aynı yöntemleri kullanarak tutarlı sonuçlar elde edebilmesi — bir bulgunun gerçek olup olmadığının temel sınaması.", defEn:"The ability of an independent researcher to obtain consistent results using the same methods — a core test of whether a finding is real." },

    // --- misconduct ---
    { id:"plagiarism", topic:"misconduct", tr:"İntihal", en:"Plagiarism", def:"Başkasına ait sözleri, verileri veya fikirleri atıf yapmadan kendine aitmiş gibi sunmak.", defEn:"Presenting someone else's words, data, or ideas as your own without attribution." },
    { id:"data-fabrication", topic:"misconduct", tr:"Veri Uydurma", en:"Data fabrication", def:"Aslında hiç toplanmamış veri veya sonuçları uydurmak.", defEn:"Inventing data or results that were never actually collected." },
    { id:"data-falsification", topic:"misconduct", tr:"Veri Çarpıtma", en:"Data falsification", def:"Gerçek araştırma materyallerini veya verilerini, sonuçlar yanlış yansıtılacak şekilde değiştirmek.", defEn:"Manipulating real research materials or data so results are misrepresented." },
    { id:"duplicate-publication", topic:"misconduct", tr:"Mükerrer Yayın", en:"Duplicate publication", def:"Aynı çalışmayı, bildirimde bulunmaksızın birden fazla yerde büyük ölçüde aynı haliyle yayımlamak.", defEn:"Publishing substantially the same work in more than one venue without disclosure." },
    { id:"ffp", topic:"misconduct", tr:"FFP (Uydurma, Çarpıtma, İntihal)", en:"FFP (Fabrication, Falsification, Plagiarism)", def:"ABD Araştırma Bütünlüğü Ofisi gibi kurumlarca araştırma etiği ihlali olarak resmen tanımlanan üç davranış biçimi — dürüst hata veya bilimsel görüş ayrılıkları bilinçli olarak dışarıda tutulur.", defEn:"The three forms of behavior formally defined as research misconduct by bodies like the US Office of Research Integrity — deliberately excluding honest error or differences of scientific opinion." },
    { id:"self-plagiarism", topic:"misconduct", tr:"Kendi Kendine İntihal", en:"Self-plagiarism (text recycling)", def:"Kişinin daha önce yayımlanmış kendi metninin veya verisinin önemli bölümlerini, bildirimde bulunmadan veya atıf yapmadan yeniymiş gibi yeniden kullanması.", defEn:"Reusing substantial portions of one's own previously published text or data as if new, without disclosure or citation." },
    { id:"salami-slicing", topic:"misconduct", tr:"Salam Dilimleme", en:"Salami slicing", def:"Tek, bütünlüklü bir çalışmayı, yayın sayısını şişirmek amacıyla birden fazla makalede en küçük yayımlanabilir birimlere bölmek.", defEn:"Splitting a single coherent study into the minimum publishable units across multiple papers to inflate publication count." },
    { id:"image-manipulation", topic:"misconduct", tr:"Görüntü Manipülasyonu", en:"Inappropriate image manipulation", def:"Şekilleri (örn. jeller, mikrograflar), altta yatan veriyi yanlış yansıtacak şekilde, standart ve tek biçimde uygulanan düzeltmelerin ötesinde değiştirmek.", defEn:"Altering figures (e.g. gels, micrographs) beyond standard, uniformly-applied adjustments in a way that misrepresents the underlying data." },
    { id:"ghost-guest-authorship", topic:"misconduct", tr:"Hayalet ve Konuk Yazarlık", en:"Ghost and guest authorship", def:"Hayalet yazarlık, önemli katkı sağlayan birini yazar listesinden çıkarır; konuk (veya hediye) yazarlık ise yazarlık kriterlerini karşılamayan birine yazarlık kredisi verir — ikisi de yazarlık standartlarını ihlal eder.", defEn:"Ghost authorship omits someone who made a substantial contribution; guest (or gift) authorship credits someone who did not meet authorship criteria — both violate authorship standards." },
    { id:"retraction", topic:"misconduct", tr:"Geri Çekme", en:"Retraction", def:"Yayımlanmış bir makalenin dergi editörleri veya yazarlar tarafından resmen geri çekilmesi; genellikle çalışmanın temelden güvenilmez veya etik dışı bulunması durumunda uygulanır.", defEn:"The formal withdrawal of a published paper by journal editors or authors, typically issued when the work is found to be fundamentally unreliable or unethical." },
    { id:"whistleblowing", topic:"misconduct", tr:"İhbarcılık", en:"Whistleblowing", def:"Şüphelenilen bir araştırma etiği ihlalinin uygun kurumsal veya editöryal kanallar üzerinden bildirilmesi — araştırmanın kendi kendini düzeltmesinin korunan ve gerekli bir parçası.", defEn:"Reporting suspected research misconduct through appropriate institutional or editorial channels — a protected and necessary part of research self-correction." },

    // --- authorship ---
    { id:"authorship-criteria", topic:"authorship", tr:"Yazarlık Kriterleri", en:"Authorship criteria", def:"ICMJE standardı: çalışmaya önemli katkı sağlamak; taslağını hazırlamak veya eleştirel biçimde gözden geçirmek; yayımlanan sürümü son haliyle onaylamak; ve çalışmadan hesap verebilir olmayı kabul etmek. Dördünün de karşılanması gerekir.", defEn:"The ICMJE standard: substantial contribution to the work; drafting or critically revising it; final approval of the published version; and agreement to be accountable for it. All four must be met." },
    { id:"citation", topic:"authorship", tr:"Atıf", en:"Citation", def:"Sözleri veya fikirleri kullanılan bir kaynağın resmi olarak belirtilmesi.", defEn:"A formal acknowledgment of a source whose words or ideas were used." },
    { id:"impact-factor", topic:"authorship", tr:"Etki Faktörü", en:"Impact factor", def:"Bir derginin makalelerinin ortalama olarak ne sıklıkla atıf aldığını yansıtan bir ölçüt.", defEn:"A metric reflecting how often a journal's articles are cited on average." },
    { id:"corresponding-author", topic:"authorship", tr:"Sorumlu Yazar", en:"Corresponding author", def:"Yayımdan önce ve sonra tüm ortak yazarlar adına dergiyle yazışma, başvuru ve iletişimi yürütmekle görevlendirilen yazar.", defEn:"The author designated to handle correspondence, submission, and communication with the journal on behalf of all co-authors before and after publication." },
    { id:"acknowledgments", topic:"authorship", tr:"Teşekkür", en:"Acknowledgments", def:"Katkısı yazarlık eşiğini karşılamayan destekçilerin — fon sağlayanlar, teknik yardımcılar, dil/yazım kontrolü yapanlar — belirtildiği bölüm.", defEn:"A section crediting contributors — funders, technical assistants, proofreaders — whose input did not meet the threshold for authorship." },
    { id:"predatory-journal", topic:"authorship", tr:"Yağmacı Dergi", en:"Predatory journal", def:"Açık erişim modelini istismar ederek yayın ücreti talep eden, buna karşılık gerçek anlamda çok az veya hiç hakem değerlendirmesi ile editöryal hizmet sunmayan dergi.", defEn:"A journal that charges publication fees while providing little or no genuine peer review or editorial service, exploiting the open-access model." },
    { id:"preprint", topic:"authorship", tr:"Ön Baskı", en:"Preprint", def:"Resmi hakem değerlendirmesinden önce herkese açık olarak paylaşılan araştırma metni; hızlı yayılmayı sağlarken topluluktan geri bildirim almaya da olanak tanır.", defEn:"A research manuscript shared publicly before formal peer review, allowing rapid dissemination while inviting community feedback." },
    { id:"open-access", topic:"authorship", tr:"Açık Erişim", en:"Open access", def:"Makalelerin okuyuculara ücretsiz sunulduğu; genellikle okuyucu aboneliği yerine yazar veya kurum ödemeleriyle finanse edilen bir yayıncılık modeli.", defEn:"A publishing model in which articles are freely available to readers, typically funded through author or institutional publication charges rather than reader subscriptions." },
    { id:"orcid-doi", topic:"authorship", tr:"ORCID ve DOI", en:"ORCID and DOI", def:"ORCID, bir araştırmacı için kalıcı ve benzersiz bir kimliktir; DOI ise belirli bir yayımlanmış esere ait kalıcı ve benzersiz bir kimliktir — ikisi de araştırma çıktısı arttıkça ortaya çıkabilecek karışıklığı önler.", defEn:"ORCID is a persistent unique identifier for a researcher; a DOI is a persistent unique identifier for a specific published work — both prevent ambiguity as research output grows." },
    { id:"conflict-of-interest", topic:"authorship", tr:"Çıkar Çatışması", en:"Conflict of interest", def:"Araştırmanın yürütülmesini veya raporlanmasını uygunsuz biçimde etkileyebilecek — ya da etkiliyormuş gibi görünebilecek — mali, kişisel veya mesleki bir çıkar; bildirilmesi zorunludur.", defEn:"A financial, personal, or professional interest that could inappropriately influence — or appear to influence — the conduct or reporting of research, and which must be disclosed." },

    // --- integrity ---
    { id:"ethics-committee", topic:"integrity", tr:"Etik Kurul", en:"Research ethics committee", def:"Çalışma önerilerini onaylanmadan önce etik standartlara uygunluk açısından değerlendiren kurul.", defEn:"A body that reviews study proposals for compliance with ethical standards before approval." },
    { id:"informed-consent", topic:"integrity", tr:"Bilgilendirilmiş Onam", en:"Informed consent", def:"Bir katılımcının, araştırmanın amacını, sürecini ve risklerini açıkça anlayarak araştırmaya katılmayı gönüllü olarak kabul etmesi.", defEn:"A participant's voluntary agreement to take part in research, given with a clear understanding of its purpose, procedures, and risks." },
    { id:"data-management-plan", topic:"integrity", tr:"Veri Yönetim Planı", en:"Data management plan (DMP)", def:"Araştırma verilerinin proje boyunca ve sonrasında nasıl toplanacağını, belgeleneceğini, saklanacağını ve paylaşılacağını açıklayan resmi plan.", defEn:"A formal plan describing how research data will be collected, documented, stored, and shared throughout and after a project." },
    { id:"fair-principles", topic:"integrity", tr:"FAIR İlkeleri", en:"FAIR principles", def:"Bulunabilir, Erişilebilir, Birlikte Çalışabilir, Yeniden Kullanılabilir — araştırma verisinin başkaları tarafından etkin biçimde kullanılıp yeniden kullanılabilmesi için yol gösteren ilkeler.", defEn:"Findable, Accessible, Interoperable, Reusable — the guiding principles for managing research data so it can be effectively used and re-used by others." },
    { id:"data-retention", topic:"integrity", tr:"Veri Saklama Süresi", en:"Data retention period", def:"Doğrulamaya olanak tanımak için, ham araştırma verisi ve kayıtlarının yayımdan sonra saklanması gereken, çoğu kurum ve fon sağlayıcı tarafından zorunlu tutulan asgari süre.", defEn:"The minimum length of time raw research data and records must be kept after publication, as required by most institutions and funders, to allow verification." },
    { id:"animal-welfare-3rs", topic:"integrity", tr:"3R İlkesi", en:"The 3Rs", def:"İkame (Replacement), Azaltma (Reduction), İyileştirme (Refinement) — araştırmada hayvanların etik kullanımı için yol gösteren, kullanımlarını ve acı çekmelerini en aza indiren çerçeve.", defEn:"Replacement, Reduction, Refinement — the guiding framework for the ethical use of animals in research, minimizing their use and any suffering." },
    { id:"biosafety", topic:"integrity", tr:"Biyogüvenlik", en:"Biosafety", def:"Genetiği değiştirilmiş organizmalar dahil biyolojik ajanlara istem dışı maruziyeti veya bunların çevreye yayılmasını önlemek için tasarlanmış kurumsal uygulamalar ve muhafaza düzeyleri.", defEn:"Institutional practices and containment levels designed to prevent unintentional exposure to or release of biological agents, including genetically modified organisms." },
    { id:"dual-use-research", topic:"integrity", tr:"İkili Kullanım Araştırması", en:"Dual-use research of concern", def:"Bulguları zarar vermek amacıyla da kötüye kullanılabilecek meşru araştırma; yayımdan veya paylaşımdan önce ek denetim gerektirir.", defEn:"Legitimate research whose findings could also be misapplied to cause harm, requiring additional oversight before publication or sharing." },
    { id:"research-misconduct-investigation", topic:"integrity", tr:"Soruşturma Süreci", en:"Misconduct investigation process", def:"Bir etik ihlali iddiasının herhangi bir yaptırımdan önce değerlendirilip karara bağlandığı, genellikle iki aşamalı (ön inceleme, ardından tam soruşturma) resmi kurumsal süreç.", defEn:"The formal, typically two-stage institutional process — inquiry, then full investigation — used to assess and adjudicate a misconduct allegation before any sanction." }
  ],
  quiz: [
    // --- process ---
    { id:"q-lit-review-purpose", topic:"process", q:"Bir literatür taramasının temel amacı nedir?", qEn:"What is the primary purpose of a literature review?", opts:["Ham veri toplamak","Mevcut bilgideki boşlukları belirlemek ve yeni araştırmayı konumlandırmak","Çalışma katılımcıları bulmak","Sonuç bölümünü yazmak"], a:1, ex:"Literatür taraması, zaten bilinenleri haritalar; böylece yeni bir çalışma varsayımlara değil gerçek boşluklara karşı konumlanabilir.", exEn:"A literature review maps what is already known so a new study can position itself against real gaps, not assumptions." },
    { id:"q-hypothesis-vs-theory", topic:"process", q:"Bir araştırma hipotezini bir teoriden ayıran nedir?", qEn:"What distinguishes a research hypothesis from a theory?", opts:["Hipotez test edilemez","Teori, kapsamlı kanıtlarla desteklenmiş, iyi temellendirilmiş bir açıklamadır; hipotez ise önerilen, test edilebilir bir açıklamadır","İkisi aynı şeydir","Hipotez hiçbir kanıt gerektirmez"], a:1, ex:"Hipotez test edilecek bir başlangıç noktasıdır; teori ise zaten önemli miktarda destekleyici kanıt biriktirmiştir.", exEn:"A hypothesis is a starting point to be tested; a theory has already accumulated substantial supporting evidence." },
    { id:"q-peer-review-importance", topic:"process", q:"Hakem değerlendirmesi yayından önce neden önemli kabul edilir?", qEn:"Why is peer review considered important before publication?", opts:["Bir makalenin asla geri çekilmeyeceğini garanti eder","Sonuçlar kamuya açık kayda geçmeden önce kalite ve geçerlilik üzerinde bağımsız bir kontrol sağlar","Revizyon ihtiyacını ortadan kaldırır","Literatür taramasının yerini alır"], a:1, ex:"Hakem değerlendirmesi bir garanti değil, bir kalite filtresidir — hatalı veya yanıltıcı sonuç riskini azaltır ama tamamen ortadan kaldırmaz.", exEn:"Peer review is a quality filter, not a guarantee — it reduces but does not eliminate the risk of flawed or misleading results." },
    { id:"q-reliability-vs-validity", topic:"process", q:"Araştırma tasarımında güvenilirliği geçerlilikten ayıran nedir?", qEn:"What distinguishes reliability from validity in research design?", opts:["İkisi aynı şeydir","Güvenilirlik bir ölçümün tutarlılığıdır; geçerlilik ise ölçtüğünü iddia ettiği şeyi gerçekten ölçüp ölçmediğidir","Geçerlilik yalnızca nitel araştırmada geçerlidir","Güvenilirlik yalnızca hakem değerlendirmesinde önemlidir"], a:1, ex:"Bir ölçüm, geçerli olmadan da yüksek düzeyde güvenilir olabilir — örneğin her zaman 2 kg eksik gösteren bir terazi çok tutarlıdır ama yanlıştır. Güvenilir sonuçlar için ikisi de gereklidir.", exEn:"A measurement can be highly reliable (consistent) without being valid — e.g. a scale that's always off by 2kg gives very consistent, but wrong, readings. Trustworthy results need both." },
    { id:"q-independent-variable", topic:"process", q:"Azotlu gübre dozunun ürün verimini etkileyip etkilemediğini test eden bir deneyde bağımsız değişken nedir?", qEn:"In an experiment testing whether nitrogen fertilizer dose affects crop yield, what is the independent variable?", opts:["Ürün verimi","Azotlu gübre dozu","Toprak pH'ı","Tarla konumu"], a:1, ex:"Bağımsız değişken, araştırmacının bilinçli olarak değiştirdiği şeydir (gübre dozu); verim ise buna tepki olarak ölçülen bağımlı değişkendir.", exEn:"The independent variable is what the researcher deliberately manipulates (fertilizer dose); yield is the dependent variable being measured in response." },

    // --- misconduct ---
    { id:"q-misconduct-forms", topic:"misconduct", q:"Aşağıdakilerden hangisi bir araştırma etiği ihlali biçimidir?", qEn:"Which of the following is a form of research misconduct?", opts:["Hakem değerlendirmesi","Veri uydurma","Önceki çalışmalara atıf yapmak","Hipotez testi"], a:1, ex:"Uydurma — hiç toplanmamış veriyi icat etmek — çarpıtma ve intihalle birlikte araştırma etiği ihlalinin temel kategorilerinden biridir.", exEn:"Fabrication — inventing data that was never collected — is one of the core categories of research misconduct, alongside falsification and plagiarism." },
    { id:"q-duplicate-pub", topic:"misconduct", q:"'Mükerrer yayın' nedir?", qEn:"What is 'duplicate publication'?", opts:["Olumsuz sonuçlarla bir makale yayımlamak","Aynı makaleyi bildirimde bulunmadan birden fazla dergiye göndermek","Kendi önceki çalışmasına atıf yapmak","Açık erişim yayımlamak"], a:1, ex:"Mükerrer yayın, literatürün bütününü yanlış yansıtır ve doğrudan veri manipülasyonu olmasa bile etik ihlali olarak kabul edilir.", exEn:"Duplicate publication misrepresents the body of literature and is treated as misconduct even without direct data manipulation." },
    { id:"q-fabrication-vs-falsification", topic:"misconduct", q:"Veri uydurma ile veri çarpıtma arasındaki temel fark nedir?", qEn:"What is the key difference between data fabrication and data falsification?", opts:["Fark yoktur","Uydurma var olmayan veriyi icat eder; çarpıtma gerçek veriyi veya sonuçları değiştirir","Çarpıtma yasaldır, uydurma değildir","Uydurma yalnızca nitel araştırmaya uygulanır"], a:1, ex:"Uydurma veriyi yoktan var eder; çarpıtma ise gerçekten toplanmış veriyi bozar.", exEn:"Fabrication creates data from nothing; falsification distorts data that was genuinely collected." },
    { id:"q-salami-slicing", topic:"misconduct", q:"Araştırma yayınında 'salam dilimleme' nedir?", qEn:"What is 'salami slicing' in research publication?", opts:["Büyük bir veri setini tek, kapsamlı bir makale olarak yayımlamak","Tek, bütünlüklü bir çalışmayı yayın sayısını şişirmek için en küçük yayımlanabilir birimlere bölmek","Doku örneği hazırlama tekniği","Yayımdan sonra bir makaleyi geri çekmek"], a:1, ex:"Salam dilimleme, tek bir çalışma bütününden gelen yayın sayısını yapay olarak çoğaltır; bu da literatürü parçalar ve hakemlerin zamanını boşa harcar.", exEn:"Salami slicing artificially multiplies publication count from a single body of work, fragmenting the literature and wasting reviewers' time." },
    { id:"q-ghost-guest", topic:"misconduct", q:"'Hayalet' yazarlık ile 'konuk' yazarlık arasındaki fark nedir?", qEn:"What is the difference between 'ghost' and 'guest' authorship?", opts:["İkisi de aynı ihlaldir","Hayalet yazarlık gerçek bir katkı sahibini dışarıda bırakır; konuk yazarlık ise yazarlık kriterlerini karşılamayan birine kredi verir","Hayalet yazarlık bildirilirse kabul edilebilir","Konuk yazarlık yalnızca sorumlu yazarlar için geçerlidir"], a:1, ex:"İkisi de yazar listesini zıt yönlerde bozar — hayalet yazarlık gerçek bir katkı sahibini gizlerken, konuk (veya hediye) yazarlık genellikle kıdem veya karşılıklılık nedeniyle hak etmeyen birini ekler.", exEn:"Both distort the authorship list in opposite directions — ghost authorship hides a real contributor, while guest (or gift) authorship adds someone undeserving, often for seniority or reciprocity." },

    // --- authorship ---
    { id:"q-authorship-disqualify", topic:"authorship", q:"Çoğu yazarlık kılavuzuna (örn. ICMJE) göre, birini yazar olarak listelenmekten ne diskalifiye eder?", qEn:"Under most authorship guidelines (e.g. ICMJE), what disqualifies someone from being listed as an author?", opts:["Veri analizine katkıda bulunmak","Yalnızca fon veya genel gözetim sağlamak, hiçbir entelektüel katkı olmadan","Makalenin bir kısmını kaleme almak","Son sürümü onaylamak"], a:1, ex:"Yalnızca fon veya gözetim genellikle teşekkür bölümünde belirtilir, yazarlık kredisi olarak sayılmaz — yazarlık, esaslı bir entelektüel katkı gerektirir.", exEn:"Funding or oversight alone is usually acknowledged, not credited as authorship — authorship requires substantive intellectual contribution." },
    { id:"q-impact-factor-meaning", topic:"authorship", q:"Yüksek bir dergi 'etki faktörü' neyi gösterir?", qEn:"What does a high journal 'impact factor' indicate?", opts:["Katı biçim kurallarını","Makalelerinin ortalama olarak nispeten sık atıf aldığını","Yalnızca açık erişim yayın yaptığını","Hakem değerlendirmesi gerektirmediğini"], a:1, ex:"Etki faktörü bir atıf sıklığı ölçütüdür — bir derginin editöryal standartları veya hakem değerlendirmesinin titizliği hakkında doğrudan hiçbir şey söylemez.", exEn:"Impact factor is a citation-frequency metric — it says nothing directly about a journal's editorial standards or peer-review rigor." },
    { id:"q-icmje-four-criteria", topic:"authorship", q:"ICMJE kriterlerine göre, bir katılımcının yazar sayılabilmesi için dört koşuldan kaçını karşılaması gerekir?", qEn:"Under ICMJE criteria, how many of the four authorship conditions must a contributor meet to qualify as an author?", opts:["Yalnızca birini","Dördünden herhangi ikisini","Dördünü de","Hiçbirini — yazarlık yalnızca kıdeme göre belirlenir"], a:2, ex:"ICMJE dördünün de karşılanmasını gerektirir: çalışmaya önemli katkı; taslağını hazırlamak veya eleştirel biçimde gözden geçirmek; yayımlanan sürümü son haliyle onaylamak; ve çalışmadan hesap verebilir olmayı kabul etmek. Yalnızca bazılarını karşılamak, teşekkürü hak eder, yazarlığı değil.", exEn:"ICMJE requires all four: substantial contribution to the work; drafting or critically revising it; final approval of the published version; and agreement to be accountable for it. Meeting only some qualifies for acknowledgment, not authorship." },
    { id:"q-predatory-journal", topic:"authorship", q:"Yağmacı bir dergiyi meşru bir açık erişim dergisinden tipik olarak ne ayırır?", qEn:"What typically distinguishes a predatory journal from a legitimate open-access journal?", opts:["Yağmacı dergiler hiçbir zaman ücret talep etmez","Yağmacı dergiler yayın ücreti alırken gerçek anlamda çok az veya hiç hakem değerlendirmesi sunmaz","Yağmacı dergiler yalnızca basılı olarak yayımlanır","Anlamlı bir fark yoktur"], a:1, ex:"Yağmacı dergiler, yazarın ödediği açık erişim modelini istismar ederek editöryal kaliteden çok ücrete öncelik verir — yayın baskısı altındaki erken kariyer araştırmacıları için gerçek bir risktir.", exEn:"Predatory journals exploit the author-pays open-access model, prioritizing fees over editorial quality — a real risk for early-career researchers under publication pressure." },
    { id:"q-preprint", topic:"authorship", q:"Ön baskı (preprint) nedir?", qEn:"What is a preprint?", opts:["Bir makalenin nihai, hakem değerlendirmesinden geçmiş yayımlanmış sürümü","Resmi hakem değerlendirmesinden önce herkese açık paylaşılan bir araştırma metni","Geri çekilmiş bir makale","Bir derginin yazım kılavuzu"], a:1, ex:"Ön baskılar hızlı yayılmayı ve topluluktan geri bildirim almayı sağlar; ancak hakem değerlendirmesinden geçmiş yayınların aksine henüz resmi olarak denetlenmemiştir — bu uyarı akılda tutularak okunmalıdır.", exEn:"Preprints accelerate dissemination and invite community feedback, but — unlike peer-reviewed publications — haven't yet been formally vetted, so they should be read with that caveat." },

    // --- integrity ---
    { id:"q-3rs", topic:"integrity", q:"'3R' ilkesi (İkame, Azaltma, İyileştirme) neyi yönetir?", qEn:"What do the '3Rs' (Replacement, Reduction, Refinement) govern?", opts:["Veri depolama formatlarını","Araştırmada hayvanların etik kullanımını","Hakem değerlendirme aşamalarını","Atıf stillerini"], a:1, ex:"3R ilkesi hayvan araştırmasının etik asgarisini çerçeveler: mümkünse hayvan modellerini ikame et, kullanılan sayıyı azalt ve acıyı en aza indirmek için prosedürleri iyileştir.", exEn:"The 3Rs frame the ethical minimum for animal research: replace animal models where possible, reduce the number used, and refine procedures to minimize suffering." },
    { id:"q-fair-principles", topic:"integrity", q:"FAIR ilkeleri öncelikle neyle ilgilidir?", qEn:"What are the FAIR principles primarily concerned with?", opts:["Yazarlık kredisinin adil dağıtımı","Araştırma verisini Bulunabilir, Erişilebilir, Birlikte Çalışabilir ve Yeniden Kullanılabilir hale getirmek","Adil hakem değerlendirme süreleri","Araştırma grupları arasında eşit fonlama"], a:1, ex:"FAIR bir veri yönetimi standardıdır, yazarlık veya fonlama ilkesi değildir — verinin bir proje bittikten çok sonra bile başkaları (ve gelecekteki siz) tarafından kullanılabilir olmasıyla ilgilidir.", exEn:"FAIR is a data-management standard, not an authorship or funding principle — it's about making data usable by others (and your future self) long after a project ends." },
    { id:"q-ethics-committee-purpose", topic:"integrity", q:"Bir çalışma başlamadan önce bir etik kurulun öneriyi incelemesinin amacı nedir?", qEn:"What is the purpose of a research ethics committee reviewing a proposal before a study begins?", opts:["Makalenin yazım stilini iyileştirmek","Önerilen araştırmanın, özellikle katılımcı/denek refahı açısından etik standartları karşılayıp karşılamadığını değerlendirmek","Yazarlık sırasını belirlemek","Çalışmanın bütçesini hesaplamak"], a:1, ex:"Etik kurullar, geri dönüşü olmayan hale gelmeden önce onam, refah ve risk gibi etik sorunları yakalamak için vardır — bilimsel kaliteyi hakemlik etmek için değil.", exEn:"Ethics committees exist to catch ethical problems — consent, welfare, risk — before they become irreversible, not to referee scientific quality." },
    { id:"q-dual-use", topic:"integrity", q:"'İkili kullanım araştırması' neyi ifade eder?", qEn:"What does 'dual-use research of concern' refer to?", opts:["İki farklı kurum tarafından fonlanan araştırma","Bulguları zarar vermek amacıyla da kötüye kullanılabilecek meşru araştırma","Aynı anda iki dergide yayımlanan bir çalışma","İki kurumda yürütülen araştırma"], a:1, ex:"İkili kullanım endişeleri ek denetim gerektirir — örneğin belirli yöntem ayrıntılarının yayımlanmasından önce — çünkü alanı ilerleten aynı bilgi zararlı amaçlarla da yeniden kullanılabilir.", exEn:"Dual-use concerns require extra oversight — for example before publishing certain methodological detail — precisely because the same knowledge that advances the field could be repurposed harmfully." },
    { id:"q-misconduct-investigation", topic:"integrity", q:"Resmi bir araştırma etiği ihlali soruşturmasının tipik ilk aşaması nedir?", qEn:"What is typically the first stage of a formal research misconduct investigation?", opts:["Şüphelenilen araştırmacının derhal işten çıkarılması","Tam bir soruşturmanın gerekip gerekmediğini belirlemek için ön inceleme","Araştırmacının tüm makalelerinin kamuya açık şekilde geri çekilmesi","Yalnızca fon sağlayan kuruma bildirim yapılması, iç inceleme yapılmadan"], a:1, ex:"Çoğu kurumsal süreç, bir ön inceleme ile başlar; ancak bu yeterli temel bulursa tam ve daha resmi bir soruşturmaya geçilir — asılsız iddialara karşı koruma sağlarken gerçek iddiaları da ciddiye alır.", exEn:"Most institutional processes start with a fact-finding inquiry; only if that finds sufficient basis does it escalate to a full, more formal investigation — protecting against unfounded allegations while still taking them seriously." },

    // --- process (ek) ---
    { id:"q-research-design-purpose", topic:"process", q:"Bir araştırma deseni temel olarak neyi tanımlar?", qEn:"What does a research design primarily define?", opts:["Sadece istatistiksel testi","Çalışmanın bileşenlerinin tutarlı ve mantıklı biçimde nasıl bir araya getirileceğini","Yalnızca örneklem büyüklüğünü","Makalenin biçimlendirmesini"], a:1, ex:"Araştırma deseni, soru, yöntem, veri toplama ve analizi tutarlı bir bütün halinde birleştiren genel plandır.", exEn:"Research design is the overall plan that brings the question, methods, data collection, and analysis together into a coherent whole." },
    { id:"q-research-question-quality", topic:"process", q:"İyi tanımlanmış bir araştırma sorusunun temel özelliği nedir?", qEn:"What is the key characteristic of a well-defined research question?", opts:["Mümkün olduğunca geniş ve belirsiz olması","Odaklanmış ve cevaplanabilir olması","Yalnızca evet/hayır ile cevaplanabilmesi","Zaten bilinen bir cevaba sahip olması"], a:1, ex:"Araştırma sorusu ne kadar odaklanmış ve cevaplanabilir olursa, ondan türetilecek hipotez ve yöntem de o kadar net olur.", exEn:"The more focused and answerable a research question is, the clearer the hypothesis and methodology derived from it will be." },
    { id:"q-dependent-variable", topic:"process", q:"Bir deneyde bağımlı değişken neyi ifade eder?", qEn:"In an experiment, what does the dependent variable represent?", opts:["Araştırmacının bilinçli olarak değiştirdiği koşulu","Bağımsız değişkendeki değişime tepki olarak ölçülen sonucu","Deneyin yapıldığı yeri","Katılımcı sayısını"], a:1, ex:"Bağımlı değişken, bağımsız değişkenin etkisini gözlemlemek için ölçülen sonuç değişkenidir — nedeni değil sonucu temsil eder.", exEn:"The dependent variable is the outcome measured to observe the effect of the independent variable — it represents the effect, not the cause." },
    { id:"q-control-group-role", topic:"process", q:"Bir deneyde kontrol grubunun rolü nedir?", qEn:"What is the role of a control group in an experiment?", opts:["Test edilen uygulamayı en yoğun şekilde almak","Test edilen uygulamayı almadan karşılaştırma noktası oluşturmak","Sonuçları istatistiksel olarak analiz etmek","Araştırma sorusunu belirlemek"], a:1, ex:"Kontrol grubu olmadan, gözlemlenen bir değişikliğin gerçekten uygulamadan mı yoksa başka bir etkenden mi kaynaklandığını ayırt etmek mümkün değildir.", exEn:"Without a control group, it's impossible to distinguish whether an observed change actually came from the treatment or from some other factor." },
    { id:"q-replication-meaning", topic:"process", q:"Bir bulgunun 'tekrarlanabilir' olması ne anlama gelir?", qEn:"What does it mean for a finding to be 'replicable'?", opts:["Yalnızca aynı araştırmacı tarafından tekrar elde edilebilmesi","Bağımsız bir araştırmacının aynı yöntemlerle tutarlı sonuçlar elde edebilmesi","Bir kez yayımlandıktan sonra asla sorgulanamaması","Yalnızca büyük örneklemlerde geçerli olması"], a:1, ex:"Tekrarlanabilirlik, bilimin kendi kendini doğrulama mekanizmasının temelidir; tekrarlanamayan bulgular şüpheyle karşılanır.", exEn:"Replicability is the foundation of science's self-correcting mechanism; findings that can't be replicated are viewed with suspicion." },
    { id:"q-control-replication-why", topic:"process", q:"Bir araştırmada hem kontrol grubu hem de tekrarlanabilirlik neden önemlidir?", qEn:"Why do both a control group and replicability matter in research?", opts:["İkisi de yalnızca bütçeyi etkiler","İkisi de bir bulgunun gerçek ve güvenilir olduğuna dair güveni artırır","Yalnızca nitel araştırmada gereklidirler","İkisi de hakem değerlendirmesinin yerini alır"], a:1, ex:"Kontrol grubu nedensel iddiayı doğrular, tekrarlanabilirlik ise bu iddianın tesadüfi olmadığını gösterir — ikisi birlikte bir bulgunun güvenilirliğini oluşturur.", exEn:"A control group validates the causal claim, while replicability shows that claim wasn't a fluke — together they build confidence in a finding." },
    { id:"q-question-vs-hypothesis", topic:"process", q:"Araştırma sorusu ile araştırma hipotezi arasındaki ilişki nedir?", qEn:"What is the relationship between a research question and a research hypothesis?", opts:["Aynı şeydir, farklı isimlerle anılır","Araştırma sorusu neyin incelendiğini tanımlar; hipotez ise buna verilen test edilebilir, önerilen bir cevaptır","Hipotez sorudan önce gelir","Araştırma sorusu yalnızca nicel çalışmalarda kullanılır"], a:1, ex:"Önce odaklanmış bir araştırma sorusu belirlenir; hipotez bu sorunun olası bir cevabı olarak, test edilecek şekilde formüle edilir.", exEn:"A focused research question is defined first; the hypothesis is then formulated as a testable, proposed answer to that question." },
    { id:"q-plant-height-dependent", topic:"process", q:"Bir gübre denemesinde 'bitki boyu' ölçülen sonuç ise, hangi değişken türüdür?", qEn:"In a fertilizer trial, if 'plant height' is the measured outcome, which type of variable is it?", opts:["Bağımsız değişken","Bağımlı değişken","Kontrol değişkeni","Araştırma sorusu"], a:1, ex:"Ölçülen sonuç her zaman bağımlı değişkendir; burada bitki boyu, uygulanan gübre miktarındaki (bağımsız değişken) değişime tepki olarak ölçülür.", exEn:"The measured outcome is always the dependent variable; here plant height is measured as a response to the applied fertilizer amount (the independent variable)." },
    { id:"q-peerreview-vs-replication", topic:"process", q:"Hakem değerlendirmesi ile tekrarlanabilirlik arasındaki fark nedir?", qEn:"What is the difference between peer review and replication?", opts:["İkisi aynı süreçtir","Hakem değerlendirmesi yayından önceki bir kalite kontrolüdür; tekrarlanabilirlik ise yayından sonra bağımsız doğrulamadır","Tekrarlanabilirlik yalnızca hakemler tarafından yapılır","Hakem değerlendirmesi sonuçların doğruluğunu garanti eder"], a:1, ex:"Hakem değerlendirmesi makalenin mantığını ve yöntemini yayından önce denetler; gerçek doğrulama ancak başkaları aynı sonuçları bağımsız olarak elde ettiğinde (tekrarlanabilirlik) gerçekleşir.", exEn:"Peer review is a quality check before publication; replication is independent verification after publication — real validation happens when others obtain the same results independently." },
    { id:"q-design-choice-basis", topic:"process", q:"Araştırma deseni seçimi tipik olarak en çok neye bağlıdır?", qEn:"What does the choice of research design typically depend on most?", opts:["Araştırmacının kişisel tercihine, rastgele olarak","Araştırma sorusunun doğasına ve incelenmek istenen ilişki türüne","Yalnızca mevcut bütçeye","Derginin yayın kurallarına"], a:1, ex:"Bir deney mi, gözlemsel bir çalışma mı, yoksa tanımlayıcı bir araştırma mı gerektiği, öncelikle neyin sorulduğuna ve hangi tür kanıtın gerektiğine bağlıdır.", exEn:"Whether an experiment, observational study, or descriptive research is needed depends primarily on what is being asked and what kind of evidence is required." },

    // --- misconduct (ek) ---
    { id:"q-plagiarism-def", topic:"misconduct", q:"İntihal en doğru şekilde nasıl tanımlanır?", qEn:"What is the most accurate definition of plagiarism?", opts:["Kendi fikrini başkasıyla paylaşmak","Başkasının sözlerini, verilerini veya fikirlerini atıf yapmadan kendine aitmiş gibi sunmak","Bir makaleyi özetlemek","Bir çalışmayı yeniden üretmek"], a:1, ex:"İntihal, kaynağın kim olduğunu gizleyerek başkasının entelektüel katkısını kendine mal etmektir; kısmi cümle kopyalama da dahildir.", exEn:"Plagiarism claims someone else's intellectual contribution as your own by concealing whose it really was; this includes partial copying, not just whole passages." },
    { id:"q-ffp-acronym", topic:"misconduct", q:"FFP kısaltması araştırma etiğinde neyi temsil eder?", qEn:"What does the acronym FFP represent in research ethics?", opts:["Fon, Finans, Personel","Uydurma, Çarpıtma, İntihal","Fakülte, Fakülte Kurulu, Program","Hiçbiri"], a:1, ex:"FFP (Fabrication, Falsification, Plagiarism), çoğu resmi araştırma bütünlüğü kurumunun araştırma etiği ihlali olarak tanımladığı üç temel kategoridir.", exEn:"FFP (Fabrication, Falsification, Plagiarism) is the core triad that most formal research integrity bodies define as research misconduct." },
    { id:"q-self-plagiarism-why", topic:"misconduct", q:"'Kendi kendine intihal' neden bir sorun olarak kabul edilir, kaynak zaten yazarın kendisiyse?", qEn:"Why is 'self-plagiarism' considered a problem, if the source is the author's own work?", opts:["Hiçbir zaman sorun değildir","Bildirilmeden yeniden kullanım, yayın kaydını yanıltabilir ve telif haklarını ihlal edebilir","Yalnızca farklı bir dilde yapılırsa sorundur","Yalnızca öğrenciler için geçerlidir"], a:1, ex:"Yazar olsa bile, önceki yayımlanmış metnin bildirilmeden yeniden kullanılması literatürün özgünlüğünü bozar ve genellikle yayıncıyla yapılan telif anlaşmasını ihlal eder.", exEn:"Undisclosed reuse — even of one's own text — can mislead the publication record and often violates copyright agreements with the original publisher." },
    { id:"q-image-manipulation-line", topic:"misconduct", q:"Bir şekildeki (örn. jel görüntüsü) parlaklık ve kontrastın tüm görüntüye eşit biçimde uygulanması genellikle kabul edilebilirken, hangisi kabul edilemez?", qEn:"Uniform brightness/contrast adjustments applied to an entire image (e.g. a gel) are usually acceptable — which of these is not?", opts:["Görüntünün yalnızca bir bölümünün seçici olarak koyulaştırılması veya silinmesi","Görüntünün ölçek çubuğunu eklemek","Görüntüyü PDF olarak kaydetmek","Görüntüye başlık eklemek"], a:0, ex:"Seçici, yerel düzenlemeler (bir bandı silmek, belirli bir bölgeyi koyulaştırmak) veriyi olduğundan farklı gösterir; oysa tüm görüntüye eşit uygulanan genel ayarlar kabul edilebilir kabul edilir.", exEn:"Selective, local edits (erasing a band, darkening one region) misrepresent the underlying data, whereas adjustments applied equally to the whole image are considered acceptable." },
    { id:"q-retraction-meaning", topic:"misconduct", q:"Bir makalenin geri çekilmesi ne anlama gelir?", qEn:"What does the retraction of a paper mean?", opts:["Makalenin yalnızca revize edildiği","Makalenin yayımcı veya yazarlar tarafından resmen geçersiz ilan edildiği","Makalenin başka bir dergiye taşındığı","Makalenin ücretsiz hale getirildiği"], a:1, ex:"Geri çekme, genellikle çalışmanın temelden güvenilmez veya etik dışı bulunması durumunda uygulanan, literatürdeki kaydı düzeltme mekanizmasıdır.", exEn:"Retraction is the record-correction mechanism typically used when a study is found to be fundamentally unreliable or unethical." },
    { id:"q-whistleblowing-first-step", topic:"misconduct", q:"Bir araştırmacı, bir meslektaşının veri uydurduğundan şüpheleniyorsa, uygun ilk adım genellikle nedir?", qEn:"If a researcher suspects a colleague fabricated data, what is usually the appropriate first step?", opts:["Sosyal medyada duyurmak","Doğrudan yüzleşip suçlamak","Kurumun belirlediği resmi kanallar aracılığıyla bildirimde bulunmak","Görmezden gelmek, kendi işini etkilemesin diye"], a:2, ex:"İhbarcılık, kurumsal veya editöryal kanallar üzerinden yapıldığında hem adil bir soruşturma sürecini başlatır hem de ihbarcıyı korur.", exEn:"Whistleblowing through institutional or editorial channels both launches a fair investigation process and protects the person reporting it." },
    { id:"q-qrp-vs-ffp", topic:"misconduct", q:"Salam dilimleme ve öz-intihal gibi davranışlar neden genellikle 'FFP' kadar ağır olmasa da sorunlu kabul edilir?", qEn:"Why are behaviors like salami slicing and self-plagiarism often considered problematic even though they're not as severe as FFP?", opts:["Hiçbir zaman sorunlu değildirler","Doğrudan veri uydurmasalar da literatürün bütünlüğünü ve yayın kaydının güvenilirliğini zedelerler","Yalnızca eski dergilerde sorun oluştururlar","Yasal olarak yasaktırlar, FFP değildir"], a:1, ex:"Bunlara genellikle 'şüpheli araştırma uygulamaları' (QRP) denir — doğrudan uydurma olmasalar da bilimsel kaydı çarpıtırlar.", exEn:"These are generally called 'questionable research practices' (QRPs) — while not direct fabrication, they still distort the integrity of the scientific record." },
    { id:"q-image-manip-as-falsification", topic:"misconduct", q:"Uygunsuz görüntü manipülasyonu, veri çarpıtmasının hangi biçimi olarak değerlendirilebilir?", qEn:"Inappropriate image manipulation can be considered a form of which kind of data misconduct?", opts:["Bir biçimi değildir, tamamen ayrı bir kategoridir","Görsel verinin, altta yatan gerçekliği yanlış yansıtacak şekilde değiştirilmesi olduğu için bir çarpıtma biçimidir","Yalnızca dijital dergilerde geçerlidir","Yalnızca fabrikasyonun bir biçimidir"], a:1, ex:"Görüntü manipülasyonu, verinin (bu durumda görsel) gerçekliği yanlış yansıtacak şekilde değiştirilmesi anlamına geldiği için çarpıtma kategorisine girer.", exEn:"Image manipulation falls under falsification because it alters visual data in a way that misrepresents the underlying reality." },
    { id:"q-correction-vs-retraction", topic:"misconduct", q:"Bir 'düzeltme' ile bir 'geri çekme' arasındaki temel fark nedir?", qEn:"What is the key difference between a 'correction' and a 'retraction'?", opts:["Aynı şeydir","Düzeltme, çalışmanın temel sonuçlarını geçersiz kılmayan küçük hataları giderir; geri çekme ise çalışmanın tamamının güvenilmez olduğunu ilan eder","Düzeltme yalnızca yazarlar tarafından yapılabilir","Geri çekme daha az ciddi bir durumdur"], a:1, ex:"Düzeltme, örneğin bir tablo hatası gibi, ana bulguları etkilemeyen sorunlar içindir; geri çekme ise çalışmanın bütününe güvenilemeyeceği anlamına gelir.", exEn:"A correction fixes minor errors that don't invalidate a study's core findings; a retraction declares the entire study unreliable." },
    { id:"q-whistleblower-protection", topic:"misconduct", q:"Kurumlar neden ihbarcıları misillemeye karşı korumayı önemser?", qEn:"Why do institutions care about protecting whistleblowers from retaliation?", opts:["Yasal bir zorunluluk olmadığı için önemsizdir","Koruma olmazsa, araştırmacılar gerçek ihlalleri bildirmekten kaçınabilir ve bu da kendi kendini düzeltme mekanizmasını zayıflatır","Yalnızca büyük üniversitelerde gereklidir","İhbarcıların her zaman haklı olduğunu garanti eder"], a:1, ex:"Misilleme korkusu, gerçek ihlallerin bile bildirilmemesine yol açabilir; bu yüzden koruma, araştırmanın kendi kendini denetleme kapasitesinin bir parçasıdır.", exEn:"Fear of retaliation can discourage researchers from reporting real violations at all, weakening science's self-correction mechanism." },

    // --- authorship (ek) ---
    { id:"q-citation-purpose", topic:"authorship", q:"Bir kaynağa atıf yapmanın temel amacı nedir?", qEn:"What is the primary purpose of citing a source?", opts:["Makaleyi uzatmak","Kullanılan söz veya fikrin kaynağını resmi olarak tanımak ve okuyucunun izleyebilmesini sağlamak","Yazarın kendi fikrini gizlemek","Yalnızca dergi kurallarını karşılamak"], a:1, ex:"Atıf, entelektüel borcu tanır ve okuyucuların iddiaların dayandığı kaynağa geri dönebilmesini sağlar — bilimsel şeffaflığın temelidir.", exEn:"Citation formally acknowledges intellectual debt and lets readers trace claims back to their source — it's foundational to scientific transparency." },
    { id:"q-corresponding-author-role", topic:"authorship", q:"Sorumlu yazarın rolü nedir?", qEn:"What is the role of the corresponding author?", opts:["Çalışmaya en az katkı sağlayan kişi olmak","Dergiyle yazışma, başvuru ve iletişimi tüm ortak yazarlar adına yürütmek","Yalnızca finansmanı sağlamak","Makaleyi çevirmek"], a:1, ex:"Sorumlu yazar, yayım süreci boyunca ve sonrasında dergiyle iletişimin tek noktasıdır; bu rol mutlaka en kıdemli yazara ait olmak zorunda değildir.", exEn:"The corresponding author is the single point of contact with the journal throughout and after publication; this role isn't necessarily held by the most senior author." },
    { id:"q-acknowledgments-use", topic:"authorship", q:"Teşekkür bölümü hangi tür katkıları belirtmek için kullanılır?", qEn:"What kind of contributions does an acknowledgments section typically credit?", opts:["Yazarlık kriterlerini tam olarak karşılayan katkıları","Yazarlık eşiğini karşılamayan ama yine de değerli olan katkıları (fon, teknik destek gibi)","Yalnızca kurum isimlerini","Hiçbir şeyi, yalnızca biçimsel bir bölümdür"], a:1, ex:"Teşekkür bölümü, yazarlık kriterlerinin tümünü karşılamayan ama katkısı tanınması gereken kişi ve kurumlar içindir.", exEn:"Acknowledgments are for people and institutions whose contribution — funding, technical help — doesn't meet the full threshold for authorship but still deserves recognition." },
    { id:"q-open-access-funding", topic:"authorship", q:"Açık erişim yayıncılık modelinde maliyet tipik olarak nasıl karşılanır?", qEn:"In the open-access publishing model, how are costs typically covered?", opts:["Yalnızca okuyucu abonelikleriyle","Genellikle yazar veya kurum ödemeleriyle, okuyucu için ücretsiz erişim sağlanarak","Devlet tarafından tamamen ücretsiz sağlanır","Hiçbir maliyeti yoktur"], a:1, ex:"Açık erişim modelinde makaleler okuyucuya ücretsiz sunulur; maliyet genellikle yazarın veya kurumunun ödediği bir işlem ücretiyle karşılanır.", exEn:"In open access, articles are free for readers; the cost is typically covered by a processing charge paid by the author or their institution." },
    { id:"q-orcid-purpose", topic:"authorship", q:"Bir araştırmacının farklı yayınlarda tutarlı biçimde tanınmasını ORCID nasıl sağlar?", qEn:"How does ORCID ensure a researcher is consistently recognized across different publications?", opts:["Her yayına otomatik olarak yeni bir isim atayarak","Araştırmacıya kalıcı, benzersiz bir kimlik numarası vererek, isim benzerliği veya değişikliği kaynaklı karışıklığı önleyerek","Yalnızca dergi editörleri tarafından kullanılarak","Makalelerin içeriğini kontrol ederek"], a:1, ex:"Aynı veya benzer isimli birçok araştırmacı olabileceğinden, ORCID her araştırmacıya kalıcı bir kimlik vererek yayınlarının doğru şekilde ona atfedilmesini sağlar.", exEn:"Since many researchers may share the same or similar names, ORCID gives each one a persistent identifier so their work is correctly attributed to them." },
    { id:"q-coi-disclosure-why", topic:"authorship", q:"Bir çıkar çatışmasının bildirilmesi gerekliliği neden önemlidir, çatışma araştırmayı fiilen etkilemese bile?", qEn:"Why does a conflict of interest need to be disclosed even if it didn't actually influence the research?", opts:["Önemli değildir, yalnızca etkilediğinde bildirilmelidir","Şeffaflık, okuyucuların sonuçları potansiyel önyargı ışığında değerlendirmesine olanak tanır","Yalnızca mali çıkarlar bildirilmelidir","Çıkar çatışması bildirilmesi yasal olarak zorunlu değildir"], a:1, ex:"Bildirim, çatışmanın etkisi kanıtlanmış olmasa bile okuyucunun bilgiyle karar vermesini sağlar — bu, güvenin korunmasının bir parçasıdır.", exEn:"Disclosure lets readers weigh the findings in light of potential bias, even without proof the conflict changed anything — that's part of maintaining trust." },
    { id:"q-citation-plagiarism-link", topic:"authorship", q:"Doğru atıf yapmak, intihalden nasıl korur?", qEn:"How does proper citation protect against plagiarism?", opts:["Korumaz, atıf yapmak intihali önlemez","Kaynağı açıkça belirterek, fikrin veya sözün kime ait olduğunu şeffaf hale getirir","Yalnızca doğrudan alıntılar için geçerlidir","Yalnızca kitaplar için geçerlidir"], a:1, ex:"Doğru atıf, bir fikrin nereden geldiğini açıkça gösterir; bu şeffaflık olmadan aynı içerik intihal sayılabilir.", exEn:"Proper citation makes it transparent exactly whose idea or words are being used — without that transparency, the same content could be considered plagiarism." },
    { id:"q-predatory-vs-legit-oa", topic:"authorship", q:"Meşru bir açık erişim dergisi ile yağmacı bir dergi arasındaki ayrımı yapmak neden bazen zor olabilir?", qEn:"Why can it sometimes be hard to distinguish a legitimate open-access journal from a predatory one?", opts:["İkisi de asla ücret talep etmez","İkisi de yazar ödemeli modeli kullanabilir; fark editöryal titizlik ve gerçek hakem değerlendirmesinde yatar, bu da dışarıdan hemen görünmeyebilir","Yağmacı dergiler asla İngilizce yayımlamaz","Meşru dergiler asla hızlı yayımlamaz"], a:1, ex:"Her iki tür de yazar ödemeli olabileceğinden, ayrım genellikle derginin editöryal süreçlerinin gerçek titizliğinde yatar — bu da dergi dizinlerini ve hakem listesini kontrol etmeyi gerektirir.", exEn:"Both may use an author-pays model; the real difference lies in editorial rigor and genuine peer review, which isn't always visible from the outside." },
    { id:"q-impact-factor-limitation", topic:"authorship", q:"Etki faktörünün bir sınırlılığı nedir?", qEn:"What is one limitation of the impact factor?", opts:["Hiçbir sınırlılığı yoktur, mükemmel bir kalite ölçütüdür","Birkaç çok atıf alan makale, dergideki çoğu makalenin daha az atıf almasına rağmen ortalamayı yükseltebilir","Yalnızca açık erişim dergiler için hesaplanabilir","Yıllık olarak değişmez"], a:1, ex:"Etki faktörü bir ortalama olduğundan, birkaç aşırı atıf alan makale, derginin genel makale kalitesini yanıltıcı biçimde yüksek gösterebilir.", exEn:"Because it's an average, a handful of extremely highly-cited papers can inflate it, even though most articles in that journal get far fewer citations." },
    { id:"q-doi-permanence", topic:"authorship", q:"Bir DOI'nin (Dijital Nesne Tanımlayıcısı) temel faydası nedir?", qEn:"What is the core benefit of a DOI (Digital Object Identifier)?", opts:["Makalenin ücretsiz olmasını sağlamak","Yayının web adresi değişse bile ona kalıcı ve güvenilir biçimde erişilmesini sağlamak","Yazarın kimliğini doğrulamak","Makalenin dilini belirlemek"], a:1, ex:"Web siteleri ve URL'ler zamanla değişebilir; DOI, yayına her zaman aynı kalıcı tanımlayıcı üzerinden ulaşılmasını garanti eder.", exEn:"Websites and URLs can change over time; a DOI guarantees the publication can always be reached through the same permanent identifier." },

    // --- integrity (ek) ---
    { id:"q-informed-consent-understanding", topic:"integrity", q:"Bilgilendirilmiş onamın geçerli olması için katılımcının neyi anlaması gerekir?", qEn:"For informed consent to be valid, what must the participant understand?", opts:["Yalnızca araştırmacının adını","Araştırmanın amacını, sürecini ve olası risklerini","Yalnızca araştırmanın süresini","Hiçbir şeyi, imza yeterlidir"], a:1, ex:"Onamın 'bilgilendirilmiş' sayılması için katılımcının neye katıldığını — amaç, süreç ve riskler dahil — gerçekten anlamış olması gerekir; yalnızca bir form imzalamak yeterli değildir.", exEn:"For consent to be genuinely 'informed,' the participant must actually understand what they're agreeing to — purpose, procedure, and risks — not just sign a form." },
    { id:"q-dmp-timing", topic:"integrity", q:"Bir veri yönetim planı (DMP) tipik olarak ne zaman hazırlanır?", qEn:"When is a data management plan (DMP) typically prepared?", opts:["Çalışma tamamlandıktan sonra","Genellikle proje başlamadan önce veya başlangıcında, veri yaşam döngüsünü önceden planlamak için","Yalnızca makale yayımlandıktan sonra","Yalnızca veri kaybolursa"], a:1, ex:"DMP'ler genellikle fon başvurusunun bir parçası olarak, veri toplanmadan önce hazırlanır; böylece toplama, saklama ve paylaşım baştan planlanmış olur.", exEn:"DMPs are usually prepared as part of a funding application, before data collection begins, so collection, storage, and sharing are planned from the start." },
    { id:"q-data-retention-why", topic:"integrity", q:"Veri saklama süresi gereklilikleri neden önemlidir?", qEn:"Why do data retention period requirements matter?", opts:["Önemli değildir, veriler hemen silinebilir","Ham verilerin belirli bir süre saklanması, sonuçların daha sonra doğrulanmasına veya sorgulanmasına olanak tanır","Yalnızca dijital verilere uygulanır","Yalnızca büyük veri setleri için gereklidir"], a:1, ex:"Bir bulgu daha sonra sorgulanırsa, saklanan ham veri olmadan iddiayı doğrulamak veya çürütmek mümkün olmaz.", exEn:"Without retained raw data, a finding that's later questioned can't be verified or refuted." },
    { id:"q-biosafety-focus", topic:"integrity", q:"Biyogüvenlik uygulamaları öncelikle neyi hedefler?", qEn:"What is the primary focus of biosafety practices?", opts:["Araştırma bütçesini korumak","Biyolojik ajanlara istem dışı maruziyeti veya bunların çevreye yayılmasını önlemek","Yalnızca fikri mülkiyeti korumak","Makale yazım kalitesini artırmak"], a:1, ex:"Biyogüvenlik, laboratuvar personelini, halkı ve çevreyi biyolojik ajanlardan (patojenler, GDO'lar dahil) korumaya yönelik önlemleri kapsar.", exEn:"Biosafety covers measures to protect lab personnel, the public, and the environment from biological agents, including pathogens and GMOs." },
    { id:"q-consent-vs-committee", topic:"integrity", q:"Bilgilendirilmiş onam ile etik kurul onayı arasındaki ilişki nedir?", qEn:"What is the relationship between informed consent and ethics committee approval?", opts:["Aynı şeydir","Etik kurul, araştırma önerisini onaylar; bilgilendirilmiş onam ise her bir katılımcıdan ayrı ayrı alınır — ikisi farklı ama tamamlayıcı korumalardır","Bilgilendirilmiş onam etik kurulun yerini alır","Etik kurul onayı yalnızca hayvan araştırmalarında gereklidir"], a:1, ex:"Etik kurul çalışmayı bir bütün olarak değerlendirip onaylar; bilgilendirilmiş onam ise bu onaylanmış çalışmaya her katılımcının bireysel, gönüllü katılımını sağlar.", exEn:"The ethics committee approves the study proposal as a whole; informed consent is then obtained individually from each participant — two different, complementary safeguards." },
    { id:"q-fair-vs-dmp", topic:"integrity", q:"FAIR ilkeleri ile bir veri yönetim planı arasındaki ilişki nedir?", qEn:"What is the relationship between the FAIR principles and a data management plan?", opts:["İlgisizdirler","Bir DMP genellikle verinin FAIR ilkelerine (Bulunabilir, Erişilebilir, Birlikte Çalışabilir, Yeniden Kullanılabilir) nasıl uyacağını somut olarak planlar","FAIR ilkeleri yalnızca DMP'lerden sonra ortaya çıkar","DMP, FAIR ilkelerinin yerini alır"], a:1, ex:"Bir DMP, FAIR ilkelerini soyut bir hedeften somut, uygulanabilir adımlara (dosya formatları, depolama, meta veri, paylaşım) dönüştürür.", exEn:"A DMP typically turns FAIR principles from an abstract goal into concrete steps — file formats, storage, metadata, sharing." },
    { id:"q-biosafety-vs-dualuse", topic:"integrity", q:"Biyogüvenlik ile ikili kullanım araştırması denetimi arasındaki fark nedir?", qEn:"What is the difference between biosafety and dual-use research oversight?", opts:["Aynı şeydir","Biyogüvenlik kazara maruziyeti/sızıntıyı önlemeye odaklanır; ikili kullanım denetimi ise bilginin kasıtlı olarak kötüye kullanılma riskini değerlendirir","İkisi de yalnızca hayvan araştırmalarına uygulanır","Biyogüvenlik yalnızca bitkilere uygulanır"], a:1, ex:"Biyogüvenlik kazara riskleri (sızıntı, maruziyet) yönetirken, ikili kullanım denetimi bilginin kasıtlı olarak zarar vermek için kullanılma ihtimaline odaklanır — farklı ama tamamlayıcı risk türleridir.", exEn:"Biosafety manages accidental risks (leaks, exposure), while dual-use oversight assesses the risk of information being deliberately misused — different but complementary risk types." },
    { id:"q-replacement-meaning", topic:"integrity", q:"Replacement (ikame) ilkesi pratikte ne anlama gelir?", qEn:"What does the 'Replacement' principle mean in practice?", opts:["Hayvan sayısını en aza indirmek","Mümkün olduğunda hayvan kullanımını hücre kültürü veya bilgisayar modelleri gibi alternatiflerle değiştirmek","Deney prosedürlerini daha az stresli hale getirmek","Hayvanları başka bir laboratuvara transfer etmek"], a:1, ex:"İkame, sorunun cevaplanması için canlı hayvan kullanımının gerçekten gerekli olup olmadığını sorgulamayı ve mümkünse alternatif yöntemlere yönelmeyi ifade eder.", exEn:"Replacement means questioning whether live animal use is actually necessary to answer the question, and switching to alternatives like cell culture or computer models when possible." },
    { id:"q-investigation-outcomes", topic:"integrity", q:"Tam bir soruşturma, ihlalin gerçekleştiğini doğrularsa, tipik sonuçlardan biri nedir?", qEn:"If a full investigation confirms misconduct occurred, what is one typical consequence?", opts:["Hiçbir şey değişmez","Yaptırımlar (örn. makalenin geri çekilmesi, disiplin işlemi) uygulanabilir ve bulgular ilgili taraflara (dergi, fon kuruluşu) bildirilebilir","Araştırmacı otomatik olarak ödüllendirilir","Soruşturma gizli tutulur ve hiçbir yere bildirilmez"], a:1, ex:"Doğrulanmış bir ihlal, geri çekme, disiplin işlemi ve ilgili dergi/fon kuruluşlarına bildirim gibi somut sonuçlar doğurabilir.", exEn:"A confirmed violation can lead to concrete consequences like retraction, disciplinary action, and notification to the relevant journal or funding body." },
    { id:"q-retention-vs-fair-value", topic:"integrity", q:"Veri saklama süresi dolduktan sonra bile, FAIR ilkelerine uygun paylaşılmış veri neden hâlâ değerli olabilir?", qEn:"Why can FAIR-shared data remain valuable even after its retention period has passed?", opts:["Değildir, süre dolunca veri değersizleşir","Meta-analizler, yeniden analiz veya yeni sorular için uzun vadede yeniden kullanılabilir","Yalnızca orijinal araştırmacı tarafından kullanılabilir","FAIR ilkeleri saklama süresinden sonra geçersiz olur"], a:1, ex:"İyi belgelenmiş, FAIR ilkelerine uygun veri, orijinal çalışmanın çok ötesinde — örneğin gelecekteki meta-analizlerde — değer üretmeye devam edebilir.", exEn:"Well-documented, FAIR-compliant data can continue generating value long after the original study — for example, in future meta-analyses." }
  ]
};
